router.get('/', authMiddleware, authorize(['admin', 'client']), async (req, res) => {
// ... existing code ...
router.get('/:id', authMiddleware, authorize(['admin', 'client']), async (req, res) => {
// ... existing code ...
router.post('/', authMiddleware, authorize(['admin', 'client']), async (req, res) => {
// ... existing code ...
router.put('/:id', authMiddleware, authorize(['admin', 'client']), async (req, res) => {
// ... existing code ...
router.delete('/:id', authMiddleware, authorize(['admin']), async (req, res) => {
// ... existing code ...
router.get('/stats/summary', authMiddleware, authorize(['admin', 'client']), async (req, res) => {
// ... existing code ...
} 
